// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtUnit = "avt_unit"

// AvtUnit mapped from table <avt_unit>
type AvtUnit struct {
	ID          int64            `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:单位id" json:"id,string"`
	Name        string           `gorm:"column:name;type:varchar(50);not null;comment:单位名" json:"name"`
	Level       int64            `gorm:"column:level;type:int;not null;comment:单位级别" json:"level"`
	CreateTime  time.Time        `gorm:"column:create_time;type:datetime;not null;comment:创建时间" json:"create_time"`
	UpdateTime  time.Time        `gorm:"column:update_time;type:datetime;not null;comment:更新时间" json:"update_time"`
	Address     string           `gorm:"column:address;type:varchar(50);not null;comment:单位地址" json:"address"`
	ParentID    *int64           `gorm:"column:parent_id;type:int" json:"parent_id"`
	FileList    []RelaUnitFile   `gorm:"foreignKey:UnitID" json:"file_list"`
	UserList    []SysBackendUser `gorm:"foreignKey:UnitID" json:"user_list"`
	SubUnitList []AvtUnit        `gorm:"foreignKey:ParentID" json:"sub_unit_list"`
}

// TableName AvtUnit's table name
func (*AvtUnit) TableName() string {
	return TableNameAvtUnit
}
