// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtEquipment = "avt_equipment"

// AvtEquipment mapped from table <avt_equipment>
type AvtEquipment struct {
	ID             int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Type           *int64     `gorm:"column:type;type:int;comment:设备类型" json:"type"`
	Name           *string    `gorm:"column:name;type:varchar(30)" json:"name"`
	Brand          *string    `gorm:"column:brand;type:varchar(20);comment:品牌" json:"brand"`
	PurchasingDate *string    `gorm:"column:purchasing_date;type:varchar(30);comment:购买时间" json:"purchasing_date"`
	Model          *string    `gorm:"column:model;type:varchar(50);comment:型号" json:"model"`
	ServiceLife    *int64     `gorm:"column:service_life;type:int;comment:月" json:"service_life"`
	WorkingTime    *int64     `gorm:"column:working_time;type:int;comment:使用时长" json:"working_time"`
	IsDelete       *int64     `gorm:"column:is_delete;type:int;comment:0-未删除；1-删除" json:"is_delete"`
	CreateTime     *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime     *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
	BuildingID     *int64     `gorm:"column:building_id;type:int" json:"building_id"`
	FloorID        *int64     `gorm:"column:floor_id;type:int" json:"floor_id"`
	RoomID         *int64     `gorm:"column:room_id;type:int" json:"room_id"`
	Group_         *int64     `gorm:"column:group;type:int;comment:设备组序号" json:"group"`
	IP             *string    `gorm:"column:ip;type:varchar(20)" json:"ip"`
	Status         *int64     `gorm:"column:status;type:int;comment:0-正常；1-故障；2-报废" json:"status"`
}

// TableName AvtEquipment's table name
func (*AvtEquipment) TableName() string {
	return TableNameAvtEquipment
}
