// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtOperationLog = "avt_operation_log"

// AvtOperationLog mapped from table <avt_operation_log>
type AvtOperationLog struct {
	ID         int64      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	UserID     int64      `gorm:"column:user_id;type:int unsigned;not null" json:"user_id"`
	ActionType int64      `gorm:"column:action_type;type:int;not null;comment:1-控制；2-升级程序" json:"action_type"`
	Content    string     `gorm:"column:content;type:varchar(200);not null" json:"content"`
	IP         string     `gorm:"column:ip;type:varchar(100);not null" json:"ip"`
	CreateTime *time.Time `gorm:"column:create_time;type:timestamp" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:timestamp" json:"update_time"`
}

// TableName AvtOperationLog's table name
func (*AvtOperationLog) TableName() string {
	return TableNameAvtOperationLog
}
