// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtPatrolLog = "avt_patrol_log"

// AvtPatrolLog mapped from table <avt_patrol_log>
type AvtPatrolLog struct {
	ID         int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;comment:巡检时间" json:"create_time"`
	Status     *int64     `gorm:"column:status;type:int;comment:0-正常；1-异常" json:"status"`
	Campus     *string    `gorm:"column:campus;type:varchar(50);comment:校区" json:"campus"`
	Building   *string    `gorm:"column:building;type:varchar(50);comment:大楼" json:"building"`
	Floor      *string    `gorm:"column:floor;type:varchar(20);comment:楼层" json:"floor"`
	Room       *string    `gorm:"column:room;type:varchar(50);comment:教室" json:"room"`
	Model      *string    `gorm:"column:model;type:varchar(50);comment:设备型号" json:"model"`
	Position   *string    `gorm:"column:position;type:varchar(100);comment:安装位置" json:"position"`
	IP         *string    `gorm:"column:ip;type:varchar(20);comment:IP地址" json:"ip"`
}

// TableName AvtPatrolLog's table name
func (*AvtPatrolLog) TableName() string {
	return TableNameAvtPatrolLog
}
