// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtFile = "avt_file"

// AvtFile mapped from table <avt_file>
type AvtFile struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"` // 文件ID
	Name       string    `gorm:"column:name;type:varchar(20);not null" json:"name"`                 // 文件名
	Size       int64     `gorm:"column:size;type:int;not null" json:"size"`                         // 文件大小
	Type       string    `gorm:"column:type;type:varchar(50);not null" json:"type"`                 // 文件类型
	FilePath   string    `gorm:"column:file_path;type:varchar(40);not null" json:"file_path"`       // 文件存储路径
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null" json:"create_time"`      // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null" json:"update_time"`      // 修改时间
	/*
		删除标志
		1-删除
		0-未删除
	*/
	IsDelete string `gorm:"column:is_delete;type:varchar(10);not null" json:"is_delete"`
	UnitID   string `gorm:"column:unit_id;type:text" json:"unit_id"`               // 所属单位id
	Status   string `gorm:"column:status;type:varchar(10);not null" json:"status"` // 文件状态
	File     string `gorm:"column:file;type:varchar(50);not null" json:"file"`     // 文件全名
}

// TableName AvtFile's table name
func (*AvtFile) TableName() string {
	return TableNameAvtFile
}
