// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtCourse = "avt_course"

// AvtCourse mapped from table <avt_course>
type AvtCourse struct {
	ID    int64   `gorm:"column:id;type:int;primaryKey;comment:课程编号" json:"id,string"`
	KCMC  string  `gorm:"column:KCMC;type:varchar(300);not null;comment:课程名称" json:"KCMC"`
	Title *string `gorm:"column:title;type:text" json:"title"`
	JSMC  string  `gorm:"column:JSMC;type:longtext;not null;comment:课程详情\n" json:"JSMC"`
	Logo  *string `gorm:"column:logo;type:varchar(200);comment:图片路径" json:"logo"`
	BJMC  string  `gorm:"column:BJMC;type:varchar(300);not null;comment:教室名称" json:"BJMC"`
	ZJGMC string  `gorm:"column:ZJGMC;type:varchar(300);not null;comment:老师名称" json:"ZJGMC"`
}

// TableName AvtCourse's table name
func (*AvtCourse) TableName() string {
	return TableNameAvtCourse
}
