// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtChapterKnowledge = "avt_chapter_knowledge"

// AvtChapterKnowledge mapped from table <avt_chapter_knowledge>
type AvtChapterKnowledge struct {
	ID          int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	ClassID     *string    `gorm:"column:class_id;type:varchar(40)" json:"class_id"`
	ClassName   *string    `gorm:"column:class_name;type:varchar(50)" json:"class_name"`
	BeginTime   *int64     `gorm:"column:begin_time;type:int" json:"begin_time"`
	EndTime     *int64     `gorm:"column:end_time;type:int" json:"end_time"`
	Name        *string    `gorm:"column:name;type:varchar(100)" json:"name"`
	BmpBase     *string    `gorm:"column:bmp_base;type:text" json:"bmp_base"`
	UpdateTime  *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
	KnowledgeID string     `gorm:"column:knowledge_id;type:varchar(50);not null" json:"knowledge_id"`
	Deleted     *int64     `gorm:"column:deleted;type:int;comment:0-未删除；1-删除" json:"deleted"`
}

// TableName AvtChapterKnowledge's table name
func (*AvtChapterKnowledge) TableName() string {
	return TableNameAvtChapterKnowledge
}
