// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtWtuTimetable = "avt_wtu_timetable"

// AvtWtuTimetable mapped from table <avt_wtu_timetable>
type AvtWtuTimetable struct {
	ID    int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Wid   *string `gorm:"column:wid;type:varchar(40)" json:"wid"`
	Kch   *string `gorm:"column:kch;type:varchar(20)" json:"kch"`
	Bh    *string `gorm:"column:bh;type:varchar(20)" json:"bh"`
	Xm    *string `gorm:"column:xm;type:varchar(60)" json:"xm"`
	Xn    *string `gorm:"column:xn;type:varchar(10)" json:"xn"`
	Xq    *string `gorm:"column:xq;type:varchar(10)" json:"xq"`
	Skzc  *string `gorm:"column:skzc;type:varchar(10)" json:"skzc"`
	Skjc  *string `gorm:"column:skjc;type:varchar(10)" json:"skjc"`
	Skxq  *int64  `gorm:"column:skxq;type:int" json:"skxq"`
	Kcm   *string `gorm:"column:kcm;type:varchar(100)" json:"kcm"`
	Ywkcm *string `gorm:"column:ywkcm;type:varchar(200)" json:"ywkcm"`
	Jasmc *string `gorm:"column:jasmc;type:varchar(50)" json:"jasmc"`
	Jxlmc *string `gorm:"column:jxlmc;type:varchar(50)" json:"jxlmc"`
}

// TableName AvtWtuTimetable's table name
func (*AvtWtuTimetable) TableName() string {
	return TableNameAvtWtuTimetable
}
