// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtTimetableEx = "avt_timetable_ex"

// AvtTimetableEx mapped from table <avt_timetable_ex>
type AvtTimetableEx struct {
	ID        int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	RoomID    *int64     `gorm:"column:room_id;type:int" json:"room_id"`
	RoomIP    *string    `gorm:"column:room_ip;type:varchar(20)" json:"room_ip"`
	Card      *string    `gorm:"column:card;type:varchar(30);comment:老师卡号" json:"card"`
	CadrID    *string    `gorm:"column:cadr_id;type:varchar(30);comment:物理卡号" json:"cadr_id"`
	TableDate *time.Time `gorm:"column:table_date;type:datetime" json:"table_date"`
	RoomName  *string    `gorm:"column:room_name;type:varchar(50)" json:"room_name"`
	CardType  *int64     `gorm:"column:card_type;type:int;comment:0-普通上课卡  ；1- 全部教室通用卡；2-单个教室通用卡" json:"card_type"`
}

// TableName AvtTimetableEx's table name
func (*AvtTimetableEx) TableName() string {
	return TableNameAvtTimetableEx
}
