// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtRoom = "avt_room"

// AvtRoom mapped from table <avt_room>
type AvtRoom struct {
	ID          int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	RoomType    *int64  `gorm:"column:room_type;type:int" json:"room_type"`
	Name        *string `gorm:"column:name;type:varchar(30)" json:"name"`
	FloorID     *int64  `gorm:"column:floor_id;type:int" json:"floor_id"`
	BuildingID  *int64  `gorm:"column:building_id;type:int" json:"building_id"`
	IsDelete    *int64  `gorm:"column:is_delete;type:int;comment:0-未删除；1-已删除" json:"is_delete"`
	IP          *string `gorm:"column:ip;type:varchar(20)" json:"ip"`
	K4Version   *string `gorm:"column:k4_version;type:varchar(40)" json:"k4_version"`
	K4Md5       *string `gorm:"column:k4_md5;type:varchar(40)" json:"k4_md5"`
	BinMd5      *string `gorm:"column:bin_md5;type:varchar(40)" json:"bin_md5"`
	LastBinMd5  *string `gorm:"column:last_bin_md5;type:varchar(40);comment:最新上传的md5" json:"last_bin_md5"`
	LastK4Md5   *string `gorm:"column:last_k4_md5;type:varchar(40);comment:最新上传的k4 md5" json:"last_k4_md5"`
	System      *string `gorm:"column:system;type:varchar(20);comment:中控系统版本：wince，linux" json:"system"`
	LiveStatus  *int64  `gorm:"column:live_status;type:int" json:"live_status"`
	SeatNum     *int64  `gorm:"column:seat_num;type:int;comment:座位数" json:"seat_num"`
	ExamSeatNum *int64  `gorm:"column:exam_seat_num;type:int;comment:考试座位数" json:"exam_seat_num"`
	RoomCode    *string `gorm:"column:room_code;type:varchar(20);comment:教室编号" json:"room_code"`
}

// TableName AvtRoom's table name
func (*AvtRoom) TableName() string {
	return TableNameAvtRoom
}
