// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtTask = "avt_task"

// AvtTask mapped from table <avt_task>
type AvtTask struct {
	ID           int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	TaskName     string    `gorm:"column:task_name;type:varchar(50);not null;comment:任务名称" json:"task_name"`
	TaskType     string    `gorm:"column:task_type;type:varchar(50);not null;comment:任务类型" json:"task_type"`
	TaskCycle    string    `gorm:"column:task_cycle;type:varchar(50);not null;comment:任务周期 now/执行一次 day每天xx点执行" json:"task_cycle"`
	Description  string    `gorm:"column:description;type:varchar(200);not null;comment:任务描述" json:"description"`
	CronSpec     string    `gorm:"column:cron_spec;type:varchar(100);not null;comment:时间表达式" json:"cron_spec"`
	Concurrent   int64     `gorm:"column:concurrent;type:tinyint;not null;comment:是否只允许一个实例" json:"concurrent"`
	Command      string    `gorm:"column:command;type:text;not null;comment:命令详情" json:"command"`
	Arge         string    `gorm:"column:arge;type:text;not null;comment:url参数" json:"arge"`
	Status       int64     `gorm:"column:status;type:tinyint;not null;comment:0停用 1启用" json:"status"`
	Timeout      int64     `gorm:"column:timeout;type:smallint;not null;comment:超时设置" json:"timeout"`
	VulnNum      int64     `gorm:"column:vuln_num;type:int;not null;comment:漏洞数量" json:"vuln_num"`
	ExecuteTimes int64     `gorm:"column:execute_times;type:int;not null;comment:累计执行次数" json:"execute_times"`
	PrevTime     int64     `gorm:"column:prev_time;type:int unsigned;not null;comment:上次执行时间" json:"prev_time"`
	CreatedTime  time.Time `gorm:"column:created_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime  time.Time `gorm:"column:updated_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
	CronConfig   *string   `gorm:"column:cron_config;type:varchar(50);comment:cron配置" json:"cron_config"`
	TaskHour     *string   `gorm:"column:task_hour;type:varchar(20)" json:"task_hour"`
	TaskDay      *int64    `gorm:"column:task_day;type:int" json:"task_day"`
	Target       *string   `gorm:"column:target;type:varchar(300)" json:"target"`
	TaskGenType  *int64    `gorm:"column:task_gen_type;type:int" json:"task_gen_type"`
}

// TableName AvtTask's table name
func (*AvtTask) TableName() string {
	return TableNameAvtTask
}
