// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtTimetableConfig = "avt_timetable_config"

// AvtTimetableConfig mapped from table <avt_timetable_config>
type AvtTimetableConfig struct {
	ID        int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Sort      *int64 `gorm:"column:sort;type:int" json:"sort"`
	StartTime *int64 `gorm:"column:start_time;type:int" json:"start_time"`
	EndTime   *int64 `gorm:"column:end_time;type:int" json:"end_time"`
}

// TableName AvtTimetableConfig's table name
func (*AvtTimetableConfig) TableName() string {
	return TableNameAvtTimetableConfig
}
