// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtTimetable = "avt_timetable"

// AvtTimetable mapped from table <avt_timetable>
type AvtTimetable struct {
	ID         int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	RoomID     *int64     `gorm:"column:room_id;type:int" json:"room_id"`
	Course     *string    `gorm:"column:course;type:varchar(30)" json:"course"`
	TeacherID  *int64     `gorm:"column:teacher_id;type:int" json:"teacher_id"`
	Weekday    *int64     `gorm:"column:weekday;type:int;comment:星期几" json:"weekday"`
	ClassIndex *int64     `gorm:"column:class_index;type:int;comment:第几节课" json:"class_index"`
	AutoStart  *int64     `gorm:"column:auto_start;type:int;comment:自动开启:1-yes;2-no" json:"auto_start"`
	AutoStop   *int64     `gorm:"column:auto_stop;type:int;comment:自动结束:1-yes;2-no" json:"auto_stop"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
	StartWeek  *int64     `gorm:"column:start_week;type:int;comment:开始周" json:"start_week"`
	EndWeek    *int64     `gorm:"column:end_week;type:int;comment:结束周" json:"end_week"`
	WeekList   *string    `gorm:"column:week_list;type:varchar(100);comment:指定周：1,2,4" json:"week_list"`
}

// TableName AvtTimetable's table name
func (*AvtTimetable) TableName() string {
	return TableNameAvtTimetable
}
