// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtLockLog = "avt_lock_log"

// AvtLockLog mapped from table <avt_lock_log>
type AvtLockLog struct {
	ID         int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	UnitNo     *string `gorm:"column:unit_no;type:varchar(20)" json:"unit_no"`
	RoomName   *string `gorm:"column:room_name;type:varchar(50)" json:"room_name"`
	LockID     *string `gorm:"column:lock_id;type:varchar(30)" json:"lock_id"`
	PeopleID   *string `gorm:"column:people_id;type:varchar(30)" json:"people_id"`
	PeopleName *string `gorm:"column:people_name;type:varchar(20)" json:"people_name"`
	CardID     *string `gorm:"column:card_id;type:varchar(20)" json:"card_id"`
	Date       *string `gorm:"column:date;type:varchar(20)" json:"date"`
	OpenType   *int64  `gorm:"column:open_type;type:int" json:"open_type"`
	AppID      *string `gorm:"column:app_id;type:varchar(20)" json:"app_id"`
	Time       *int64  `gorm:"column:time;type:bigint" json:"time"`
}

// TableName AvtLockLog's table name
func (*AvtLockLog) TableName() string {
	return TableNameAvtLockLog
}
