// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtFloor = "avt_floor"

// AvtFloor mapped from table <avt_floor>
type AvtFloor struct {
	ID         int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Floor      *string `gorm:"column:floor;type:varchar(20)" json:"floor"`
	BuildingID *int64  `gorm:"column:building_id;type:int" json:"building_id"`
	IsDelete   int64   `gorm:"column:is_delete;type:int;not null;comment:0-未删除；1-已删除" json:"is_delete"`
	Sort       *int64  `gorm:"column:sort;type:int;comment:越大越靠前" json:"sort"`
	FloorCode  *string `gorm:"column:floor_code;type:varchar(20);comment:楼层编号" json:"floor_code"`
	RoomNum    *int64  `gorm:"column:room_num;type:int;comment:教室数量" json:"room_num"`
}

// TableName AvtFloor's table name
func (*AvtFloor) TableName() string {
	return TableNameAvtFloor
}
