// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAvtSmartLock = "avt_smart_lock"

// AvtSmartLock mapped from table <avt_smart_lock>
type AvtSmartLock struct {
	ID         int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	BuildingID *int64  `gorm:"column:building_id;type:int" json:"building_id"`
	FloorID    *int64  `gorm:"column:floor_id;type:int" json:"floor_id"`
	RoomID     *int64  `gorm:"column:room_id;type:int" json:"room_id"`
	UnitNo     *string `gorm:"column:unit_no;type:varchar(20)" json:"unit_no"`
	LockID     *string `gorm:"column:lock_id;type:varchar(20)" json:"lock_id"`
	LockName   *string `gorm:"column:lock_name;type:varchar(20)" json:"lock_name"`
}

// TableName AvtSmartLock's table name
func (*AvtSmartLock) TableName() string {
	return TableNameAvtSmartLock
}
