// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOperator = "sys_operator"

// SysOperator mapped from table <sys_operator>
type SysOperator struct {
	ID           int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	OperatorNo   int64      `gorm:"column:operator_No;type:int;not null" json:"operator_No"`
	Name         *string    `gorm:"column:name;type:varchar(100);comment:运营商名称" json:"name"`
	OperatorDes  *string    `gorm:"column:operator_des;type:varchar(200);comment:运营商详情" json:"operator_des"`
	Contact      *string    `gorm:"column:contact;type:varchar(100);comment:联系人" json:"contact"`
	Address      *string    `gorm:"column:address;type:varchar(300)" json:"address"`
	Status       *int64     `gorm:"column:status;type:int;comment:0,无效的；1，有效的" json:"status"`
	CreateTime   *time.Time `gorm:"column:create_time;type:timestamp;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   *time.Time `gorm:"column:update_time;type:timestamp" json:"update_time"`
	OperatorType *int64     `gorm:"column:operator_type;type:int;comment:2-运营商；1-大客户;3-推广渠道；4-协议企业" json:"operator_type"`
	Mobile       *string    `gorm:"column:mobile;type:varchar(20)" json:"mobile"`
	Email        *string    `gorm:"column:email;type:varchar(50)" json:"email"`
	Discount     *float32   `gorm:"column:discount;type:float;default:100;comment:对于推广渠道，表示服务费分成比例；对于协议公司表示服务费优惠比例" json:"discount"`
	Earnings     int64      `gorm:"column:earnings;type:int;not null;comment:收入分成" json:"earnings"`
	DeleteFlag   *int64     `gorm:"column:delete_flag;type:int;comment:0-为删除；1-已删除" json:"delete_flag"`
}

// TableName SysOperator's table name
func (*SysOperator) TableName() string {
	return TableNameSysOperator
}
