// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysBackendUserRmsRole = "sys_backend_user_rms_roles"

// SysBackendUserRmsRole mapped from table <sys_backend_user_rms_roles>
type SysBackendUserRmsRole struct {
	ID               int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id,string"`
	RmsBackendUserID int64 `gorm:"column:rms_backend_user_id;type:int;not null" json:"rms_backend_user_id"`
	RmsRoleID        int64 `gorm:"column:rms_role_id;type:int;not null" json:"rms_role_id"`
}

// TableName SysBackendUserRmsRole's table name
func (*SysBackendUserRmsRole) TableName() string {
	return TableNameSysBackendUserRmsRole
}
