PUT http://127.0.0.1:5500/api/resource/update/3
Content-Type: application/json

{
  "name": "爱坤坤",
  "size": 5555,
  "type": "image/png",
  "file_path": "/path",
  "is_delete": 0,
  "status": "1",
  "unit_id": 1
}